//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningFCIH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.Answers = new HashSet<Answer>();
            this.Attendances = new HashSet<Attendance>();
            this.User_Quiz = new HashSet<User_Quiz>();
        }
    
        public int QuizID { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<User_Quiz> User_Quiz { get; set; }
    }
}
