//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningFCIH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User_Quiz = new HashSet<User_Quiz>();
            this.User_Subject = new HashSet<User_Subject>();
            this.User_Doctor = new HashSet<User_Doctor>();
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserGroupID { get; set; }
        public string Status { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Bio { get; set; }
    
        public virtual ICollection<User_Quiz> User_Quiz { get; set; }
        public virtual ICollection<User_Subject> User_Subject { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual ICollection<User_Doctor> User_Doctor { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
    }
}
