//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningFCIH.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string DrID { get; set; }
        public string Link { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.DateTime> StartsOn { get; set; }
        public Nullable<System.DateTime> EndsOn { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
